In [2]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import ast as ast
from IPython.display import HTML

In [4]:
bosses = pd.read_csv("./datasets/bosses.csv")

bosses = bosses.drop(columns=["description"])

In [ ]:
def path_to_image_html(path):
    return f'<img src = {path} width = 80 height = 40 style = "object-fit: cover;"/>'

HTML(bosses.to_html(escape=False, formatters={'image': path_to_image_html}))

In [ ]:
bosses.describe()

In [5]:
bosses["healthPoints"] = pd.to_numeric(bosses["healthPoints"], errors="coerce")

In [19]:
bosses

,id,name,image,region,location,drops,healthPoints
4,17f69a3ca37l0i1ukd1lq14ctafbk,"Adan, Thief Of Fire",https://eldenring.fanapis.com/images/bosses/17...,Liurnia of the Lakes,Malefactor's Evergaol,"['3.800 Runes', 'Flame of the Fell God']",2200.0
5,17f69a63610l0i1ukyx7xgx6vf0zoa,Ancient Dragon Lansseax,https://eldenring.fanapis.com/images/bosses/17...,Altus Plateau,Altus Plateau,"['60.000 Runes', ""Lansseax's Glaive""]",9087.0
6,17f69590896l0i1ul0hnmor8iyf9xd,Ancestor Spirit,https://eldenring.fanapis.com/images/bosses/17...,Limgrave,Siofra River,"['13.000 Runes', 'Ancestral Follower Ashes']",2200.0
7,17f69878c4al0i1ul0i7dsfou8igrk,Ancient Hero Of Zamor,https://eldenring.fanapis.com/images/bosses/17...,Weeping Peninsula,"Weeping Evergaol, Giant-Conquering Hero's Grave","['5,400 Runes', ""Radagon's Scarseal"", '83,000 ...",2200.0
8,17f697240ecl0i1ul21nevug9wq54e,Beast Clergyman,https://eldenring.fanapis.com/images/bosses/17...,Caelid,Crumbling Farum Azula,['N/A'],2200.0
10,17f69d4387al0i1ulpqqumwqw05j3c,Beast Of Farum Azula,https://eldenring.fanapis.com/images/bosses/17...,Limgrave,Groveside Cave,"['1000 Runes', 'Flamedrake Talisman']",1960.0
14,17f69bd3c06l0i1ulx2jxbiogta1i,Black Knife Assassin,https://eldenring.fanapis.com/images/bosses/17...,Limgrave,"Deathtouched Catacombs, Black Knife CatacombsS...","['1,600 Runes', ""Assassin's Crimson Dagger"", '...",2750.0
23,17f69e151d8l0i1uo19hl8r6l0snmo,Deathbird,https://eldenring.fanapis.com/images/bosses/17...,Limgrave,"Limgrave, Weeping Peninsula, Liurnia of the Lakes","['3,900 Runes', 'Blue-Feathered Branchsword', ...",2750.0
53,17f6953f0d5l0i1uthl5j30bc50wdo,Godrick The Grafted,https://eldenring.fanapis.com/images/bosses/17...,Limgrave,Stormveil Castle,"[""Godrick's Great Rune, Remembrance of the Gra...",6080.0
69,17f69bfa759l0i1uwfa0yrdvzcov1i,Magma Wyrm,https://eldenring.fanapis.com/images/bosses/17...,Caelid,Gael Tunnel,"['7500 Runes', 'Dragon Heart', 'Moonveil']",7000.0
95,17f696d979al0i1v1775oof02bi8oh,"Rykard, Lord Of Blasphemy",https://eldenring.fanapis.com/images/bosses/17...,Mount Gelmir,Mt. Gelmir,"['130,000 Runes', ""Rykard's Great Rune"", 'Reme...",1000000.0

In [6]:
bosses["healthPoints"].describe()

count         11.000000
mean       94402.454545
std       300362.582374
min         1960.000000
25%         2200.000000
50%         2750.000000
75%         6540.000000
max      1000000.000000
Name: healthPoints, dtype: float64

In [ ]:
print(bosses["healthPoints"].isnull().sum())

95

In [16]:
bosses["healthPoints"] = bosses["healthPoints"].fillna(0)

In [18]:
bosses["healthPoints"]

4        2200.0
5        9087.0
6        2200.0
7        2200.0
8        2200.0
10       1960.0
14       2750.0
23       2750.0
53       6080.0
69       7000.0
95    1000000.0
Name: healthPoints, dtype: float64

In [20]:
HTML(bosses.to_html(escape=False, formatters={'image': path_to_image_html}))